version: '3.7'

services:
  web:
    build:
      context: docker/build/nginx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_SERVER_NAME
      - NGINX_ENABLE_SSL
      - NGINX_FORCE_HTTPS
      - NGINX_FASTCGI_PASS=${APP_CONTAINER_NAME}:9000
      - REVIEW_MODE=${REVIEW_MODE:-false}
      - WP_BASIC_AUTH_USER=${WP_BASIC_AUTH_USER:-}
      - WP_BASIC_AUTH_PASSWORD=${WP_BASIC_AUTH_PASSWORD:-}
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - "letsencrypt:/etc/letsencrypt"
      - "$STORAGE_PATH/nginx/certs:/etc/nginx/certs"
      - "$WORDPRESS_VOLUME_PATH:/var/www/html/wordpress:delegated"
      - "$PHPMYADMIN_VOLUME_PATH:/var/www/html/phpmyadmin:delegated"
    depends_on:
      - app
    networks:
      default:
        aliases:
          - ${NGINX_SERVER_NAME}
      wordpress-shared:
        aliases:
          - ${NGINX_SERVER_NAME}

  app:
    build:
      context: docker/build/app
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    env_file:
      - .env.wp-salt
    environment:
      - WP_DEFAULT_VERSION
      - WP_SITE_URL
      - WP_EMAIL
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST=${DB_CONTAINER_NAME}
      - SMTP_HOST=${MAIL_CONTAINER_NAME}
      - SMTP_PORT=1025
      - SMTP_FROM=${WP_EMAIL}
      - SMTP_NAME=WordPress
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - "$WORDPRESS_VOLUME_PATH:/var/www/html/wordpress:delegated"
      - "$PHPMYADMIN_VOLUME_PATH:/var/www/html/phpmyadmin:delegated"
      - "$STORAGE_PATH/app/php.ini:/usr/local/etc/php/conf.d/php.ini:cached"
      - "$STORAGE_PATH/app/initdb.d:/initdb.d"
      - "$STORAGE_PATH/app/setup.d:/setup.d"
    depends_on:
      - db
    networks:
      - default
      - wordpress-shared

  db:
    build:
      context: docker/build/mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    # MySQL8以下をご利用の場合は、下記のコメントを外してください。
    # platform: linux/amd64
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - "$STORAGE_PATH/mysql/data:/var/lib/mysql"
      - "$STORAGE_PATH/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf:cached"
    networks:
      - default
      - wordpress-shared

  cron:
    build:
      context: docker/build/cron
      dockerfile: Dockerfile
    container_name: ${CRON_CONTAINER_NAME}
    init: true
    environment:
      - CONTAINER_NAME_PREFIX=${COMPOSE_PROJECT_NAME}
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - "$DOCKER_SOCKET:/var/run/docker.sock:ro"
      - "$STORAGE_PATH/cron/crontabs:/etc/crontabs"
    depends_on:
      - app
    networks:
      - default
      - wordpress-shared

  mail:
    build:
      context: docker/build/mail
      dockerfile: Dockerfile
    container_name: ${MAIL_CONTAINER_NAME}
    ports:
      - "8025:8025"
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - TZ=${TIMEZONE:-Asia/Tokyo}
    volumes:
      - maildir:/data
    depends_on:
      - app
    networks:
      - default
      - wordpress-shared

volumes:
  maildir:
  letsencrypt:

networks:
  wordpress-shared:
    external: true