version: '3.6'

services:
  web:
    build:
      context: docker/build/nginx
      dockerfile: Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_SERVER_NAME
      - NGINX_ENABLE_SSL
      - NGINX_FORCE_HTTPS
    volumes:
      - ./docker/storage/nginx/certs:/etc/nginx/certs
      - ./wordpress:/var/www/html/wordpress:delegated
      - ./phpmyadmin:/var/www/html/phpmyadmin:delegated
    depends_on:
      - app
    networks:
      default:
        aliases:
          - ${NGINX_SERVER_NAME}

  app:
    build:
      context: docker/build/app
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
    env_file:
      - .env.wp-salt
    environment:
      - WP_SITE_URL
      - WP_EMAIL
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST=db
      - SMTP_HOST=mail
      - SMTP_PORT=1025
      - SMTP_FROM=${WP_EMAIL}
      - SMTP_NAME=WordPress
    volumes:
      - ./wordpress:/var/www/html/wordpress:delegated
      - ./phpmyadmin:/var/www/html/phpmyadmin:delegated
      - ./docker/storage/app/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
      - ./docker/storage/app/initdb.d:/initdb.d
      - ./docker/storage/app/setup.d:/setup.d
    depends_on:
      - db

  db:
    build:
      context: docker/build/mysql
      dockerfile: Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./docker/storage/mysql/data:/var/lib/mysql
      - ./docker/storage/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf:cached

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    platform: linux/amd64
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
    depends_on:
      - app

volumes:
  maildir: